"""Widget registry — what the dashboard can show, and what it shows by default.

Kept separate from the routes so that adding a widget is a data change: an
entry here, a loader in loaders.py, a block in the template.
"""

WIDGET_REGISTRY: dict[str, dict] = {
    # Stats widgets
    "stats_knowledge": {
        "label": "Knowledge",
        "size": "third",
        "icon": "book-open",
        "url": "/",
        "module": "knowledge",
    },
    "stats_tasks": {
        "label": "Tasks",
        "size": "third",
        "icon": "check-square-2",
        "url": "/tasks",
        "module": "tasks",
    },
    "stats_notes": {
        "label": "Notes",
        "size": "third",
        "icon": "file-text",
        "url": "/notes",
        "module": "notes",
    },
    "stats_links": {
        "label": "Links",
        "size": "third",
        "icon": "link-2",
        "url": "/links",
        "module": "links",
    },
    "stats_vacations": {
        "label": "Vacations",
        "size": "third",
        "icon": "umbrella",
        "url": "/vacations",
        "module": "vacations",
    },
    "stats_appointments": {
        "label": "Appointments",
        "size": "third",
        "icon": "calendar-days",
        "url": "/appointments",
        "module": "appointments",
    },
    "stats_runbooks": {
        "label": "Runbooks",
        "size": "third",
        "icon": "list-ordered",
        "url": "/runbooks",
        "module": "runbooks",
    },
    "stats_snippets": {
        "label": "Snippets",
        "size": "third",
        "icon": "terminal",
        "url": "/snippets",
        "module": "snippets",
    },
    "stats_mail_templates": {
        "label": "Mail Templates",
        "size": "third",
        "icon": "mail",
        "url": "/mail-templates",
        "module": "mail_templates",
    },
    "stats_ticket_templates": {
        "label": "Ticket Templates",
        "size": "third",
        "icon": "ticket",
        "url": "/ticket-templates",
        "module": "ticket_templates",
    },
    "stats_motd": {
        "label": "MOTD",
        "size": "third",
        "icon": "message-circle",
        "url": "/motd",
        "module": "motd",
    },
    "stats_potd": {
        "label": "Picture of the Day",
        "size": "third",
        "icon": "image",
        "url": "/potd",
        "module": "potd",
    },
    "stats_eol": {
        "label": "EOL Tracker",
        "size": "third",
        "icon": "shield-check",
        "url": "/eol",
        "module": "eol",
    },
    "eol_expiring": {
        "label": "EOL Expiring",
        "size": "half",
        "icon": "shield-alert",
        "url": "/eol",
        "module": "eol",
    },
    "stats_memes": {
        "label": "Memes",
        "size": "third",
        "icon": "smile",
        "url": "/memes",
        "module": "memes",
    },
    "stats_rss": {
        "label": "RSS Feeds",
        "size": "third",
        "icon": "rss",
        "url": "/rss",
        "module": "rss",
    },
    # Content widgets
    "tasks_due": {
        "label": "Due Soon",
        "size": "half",
        "icon": "clock",
        "url": "/tasks",
        "module": "tasks",
    },
    "tasks_overdue": {
        "label": "Overdue Tasks",
        "size": "half",
        "icon": "alert-circle",
        "url": "/tasks",
        "module": "tasks",
    },
    "motd": {
        "label": "Message of the Day",
        "size": "half",
        "icon": "message-circle",
        "url": "/motd",
        "module": "motd",
    },
    "calendar_mini": {
        "label": "Upcoming",
        "size": "half",
        "icon": "calendar",
        "url": "/calendar",
        "module": None,
    },
    "calendar_widget": {
        "label": "Kalender",
        "size": "full",
        "icon": "calendar-days",
        "url": "/calendar",
        "module": None,
    },
    "sprint": {
        "label": "Sprint",
        "size": "half",
        "icon": "timer",
        "url": "/calendar",
        "module": None,
    },
    "vacation_balance": {
        "label": "Vacation Balance",
        "size": "half",
        "icon": "umbrella",
        "url": "/vacations",
        "module": "vacations",
    },
    "next_vacation": {
        "label": "Next Vacation",
        "size": "third",
        "icon": "plane",
        "url": "/vacations",
        "module": "vacations",
    },
    "appointments_upcoming": {
        "label": "Upcoming Appointments",
        "size": "half",
        "icon": "calendar-check",
        "url": "/appointments",
        "module": "appointments",
    },
    "favorites": {"label": "Favorites", "size": "half", "icon": "star", "url": "/", "module": None},
    "recent_activity": {
        "label": "Recent Activity",
        "size": "half",
        "icon": "history",
        "url": "/history",
        "module": None,
    },
    "rss_feed": {"label": "RSS", "size": "half", "icon": "rss", "url": "/rss", "module": "rss"},
    "runbook_overview": {
        "label": "Runbooks",
        "size": "half",
        "icon": "list-ordered",
        "url": "/runbooks",
        "module": "runbooks",
    },
    "quick_capture": {
        "label": "Quick Add",
        "size": "half",
        "icon": "plus-circle",
        "url": "/tasks",
        "module": None,
    },
    "bookmarks": {
        "label": "Bookmarks",
        "size": "half",
        "icon": "bookmark",
        "url": "/links",
        "module": "links",
    },
    "potd": {
        "label": "Picture of the Day",
        "size": "half",
        "icon": "image",
        "url": "/potd",
        "module": "potd",
    },
    "meme": {
        "label": "Meme of the Day",
        "size": "half",
        "icon": "smile",
        "url": "/memes",
        "module": "memes",
    },
    "redis_status": {
        "label": "Redis Cache",
        "size": "half",
        "icon": "zap",
        "url": "/settings",
        "module": None,
    },
    "tmp_usage": {
        "label": "/tmp Usage",
        "size": "third",
        "icon": "hard-drive",
        "url": None,
        "module": None,
    },
    "countdown": {
        "label": "Countdown",
        "size": "third",
        "icon": "timer",
        "url": None,
        "module": None,
    },
    "app_version": {
        "label": "App Version",
        "size": "third",
        "icon": "git-commit",
        "url": None,
        "module": None,
    },
    "repos": {
        "label": "Repositories",
        "size": "half",
        "icon": "database",
        "url": "/settings",
        "module": None,
    },
    "notes_recent": {
        "label": "Recent Notes",
        "size": "half",
        "icon": "file-text",
        "url": "/notes",
        "module": "notes",
    },
}

_DEFAULT_LAYOUT = [
    {"id": "stats_knowledge", "enabled": True, "settings": {}},
    {"id": "stats_tasks", "enabled": True, "settings": {}},
    {"id": "stats_notes", "enabled": True, "settings": {}},
    {"id": "stats_links", "enabled": True, "settings": {}},
    {"id": "stats_vacations", "enabled": True, "settings": {}},
    {"id": "stats_appointments", "enabled": True, "settings": {}},
    {"id": "stats_runbooks", "enabled": True, "settings": {}},
    {"id": "stats_snippets", "enabled": True, "settings": {}},
    {"id": "stats_mail_templates", "enabled": False, "settings": {}},
    {"id": "stats_ticket_templates", "enabled": False, "settings": {}},
    {"id": "stats_motd", "enabled": False, "settings": {}},
    {"id": "stats_potd", "enabled": False, "settings": {}},
    {"id": "stats_memes", "enabled": False, "settings": {}},
    {"id": "stats_rss", "enabled": False, "settings": {}},
    {"id": "stats_eol", "enabled": False, "settings": {}},
    {"id": "eol_expiring", "enabled": False, "settings": {"days_ahead": 90}},
    {"id": "tasks_due", "enabled": True, "settings": {"max_items": 5}},
    {"id": "tasks_overdue", "enabled": False, "settings": {"max_items": 5}},
    {"id": "motd", "enabled": True, "settings": {}},
    {"id": "calendar_mini", "enabled": True, "settings": {"days_ahead": 14}},
    {"id": "calendar_widget", "enabled": False, "settings": {}},
    {"id": "sprint", "enabled": False, "settings": {}},
    {"id": "vacation_balance", "enabled": False, "settings": {}},
    {"id": "next_vacation", "enabled": False, "settings": {}},
    {
        "id": "appointments_upcoming",
        "enabled": False,
        "settings": {"days_ahead": 14, "max_items": 5},
    },
    {"id": "favorites", "enabled": False, "settings": {"max_items": 8}},
    {"id": "recent_activity", "enabled": False, "settings": {"max_items": 8}},
    {"id": "rss_feed", "enabled": False, "settings": {"max_items": 5, "feed_id": ""}},
    {"id": "runbook_overview", "enabled": False, "settings": {"max_items": 5}},
    {"id": "quick_capture", "enabled": False, "settings": {}},
    {"id": "bookmarks", "enabled": False, "settings": {"category": "", "max_items": 8}},
    {"id": "potd", "enabled": False, "settings": {}},
    {"id": "meme", "enabled": False, "settings": {}},
    {"id": "redis_status", "enabled": False, "settings": {}},
    {"id": "tmp_usage", "enabled": False, "settings": {}},
    {"id": "countdown", "enabled": False, "settings": {"label": "", "target_date": ""}},
    {"id": "app_version", "enabled": False, "settings": {}},
    {"id": "repos", "enabled": False, "settings": {}},
    {"id": "notes_recent", "enabled": False, "settings": {"max_items": 5}},
]
